version: 2
jobs:
  build:
    docker:
      - image: markhobson/aws-eb-demo-primary
    working_directory: ~/aws-eb-demo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build artifact
          command: mvn clean package
      - run:
          name: Build Docker image
          command: docker build -t markhobson/aws-eb-demo .
      - run:
          name: Log Docker into registry
          command: docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD}
      - run:
          name: Push Docker image to registry
          command: docker push markhobson/aws-eb-demo
      - run:
          name: Configure AWS Elastic Beanstalk
          command: eb init --platform docker-17.09.1-ce --region ${AWS_DEFAULT_REGION} aws-eb-demo
      - run:
          name: Deploy Docker image to AWS Elastic Beanstalk
          command: eb deploy
